### ISSUE TITLE
Declare array with a variable size

### ISSUE THREAD

**Issue by Chen-JQ** [jordanvrtanoski/luacpp#12]
LuaLibrary.cpp : 54
    luaL_Reg reg[functions.size()+1];

Is it a new feature in C++ ?  
Why I can't compile with it ?

**Comment by jordanvrtanoski** [comment]
It's dynamic array allocation and should work if your compiler is C++17 or above. The LuaCPP library is using the C++ 17 syntax.
Can you check which version of the compiler you are using and share the exact error messages that the compiler had thrown.

**Comment by Chen-JQ** [comment]
Sorry, I didn't notice that.
I AM using C++17, but, I'm using msvc, and i have a try, Clang works for me.
Thanks a lot!

**Comment by jordanvrtanoski** [comment]
I am happy you resolved it. Let me know if you have other issues or recommendations.

**Comment by iAndyHD3** [comment]
This issue is still happening in MSVC even with c++20. Variable length array is not a new c++ feature, it's invalid c++ but supported by gcc/clang as an extension. See [VLA gcc documentation](https://gcc.gnu.org/onlinedocs/gcc/Variable-Length.html), [disable VLA in gcc](https://stackoverflow.com/questions/31710642/disable-variable-length-automatic-arrays-in-gcc) and [VLA in clang](https://stackoverflow.com/questions/17645496/are-variable-length-arrays-an-extension-in-clang-too). Please rewrite the function to use valid c++ code.

Personally I fixed this issue simply by using `std::vector` but I can't actually build all the test cases to make sure it works correctly.
